// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Setlist.Web.Data;

#nullable disable

namespace Setlist.Web.Migrations
{
    [DbContext(typeof(SetlistContext))]
    partial class SetlistContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Setlist.Web.Models.Gig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("HitAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gig", (string)null);
                });

            modelBuilder.Entity("Setlist.Web.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.ToTable("Set", (string)null);
                });

            modelBuilder.Entity("Setlist.Web.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Filepath")
                        .HasColumnType("text");

                    b.Property<int?>("SetId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Song", (string)null);
                });

            modelBuilder.Entity("Setlist.Web.Models.Set", b =>
                {
                    b.HasOne("Setlist.Web.Models.Gig", null)
                        .WithMany("Sets")
                        .HasForeignKey("GigId");
                });

            modelBuilder.Entity("Setlist.Web.Models.Song", b =>
                {
                    b.HasOne("Setlist.Web.Models.Set", null)
                        .WithMany("Songs")
                        .HasForeignKey("SetId");
                });

            modelBuilder.Entity("Setlist.Web.Models.Gig", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Setlist.Web.Models.Set", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
